// @generated by protobuf-ts 2.9.4 with parameter output_javascript_es2019
// @generated from protobuf file "bilibili/app/playerunite/v1/player.proto" (package "bilibili.app.playerunite.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ViewInfo } from "../../../playershared/playershared";
import { PlayArcConf } from "../../../playershared/playershared";
/**
 * @generated from protobuf message bilibili.app.playerunite.v1.PlayViewUniteReply
 */
export interface PlayViewUniteReply {
    /**
     * @generated from protobuf field: bilibili.playershared.PlayArcConf play_arc_conf = 2;
     */
    playArcConf?: PlayArcConf;
    /**
     * @generated from protobuf field: bilibili.playershared.ViewInfo view_info = 9;
     */
    viewInfo?: ViewInfo;
}
declare class PlayViewUniteReply$Type extends MessageType<PlayViewUniteReply> {
    constructor();
    create(value?: PartialMessage<PlayViewUniteReply>): PlayViewUniteReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayViewUniteReply): PlayViewUniteReply;
    internalBinaryWrite(message: PlayViewUniteReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.playerunite.v1.PlayViewUniteReply
 */
export declare const PlayViewUniteReply: PlayViewUniteReply$Type;
export {};
