// @generated by protobuf-ts 2.9.4 with parameter output_javascript_es2019
// @generated from protobuf file "bilibili/app/show/popular/v1/popular.proto" (package "bilibili.app.show.popular.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message bilibili.app.show.popular.v1.PopularReply
 */
export interface PopularReply {
    /**
     * @generated from protobuf field: repeated bilibili.app.show.popular.v1.Card items = 1;
     */
    items: Card[];
}
/**
 * @generated from protobuf message bilibili.app.show.popular.v1.Card
 */
export interface Card {
    /**
     * @generated from protobuf oneof: item
     */
    item: {
        oneofKind: "rcmdOneItem";
        /**
         * @generated from protobuf field: bytes rcmd_one_item = 10;
         */
        rcmdOneItem: Uint8Array;
    } | {
        oneofKind: "smallCoverV5Ad";
        /**
         * @generated from protobuf field: bytes small_cover_v5_ad = 11;
         */
        smallCoverV5Ad: Uint8Array;
    } | {
        oneofKind: "topicList";
        /**
         * @generated from protobuf field: bytes topic_list = 12;
         */
        topicList: Uint8Array;
    } | {
        oneofKind: undefined;
    };
}
declare class PopularReply$Type extends MessageType<PopularReply> {
    constructor();
    create(value?: PartialMessage<PopularReply>): PopularReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PopularReply): PopularReply;
    internalBinaryWrite(message: PopularReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.show.popular.v1.PopularReply
 */
export declare const PopularReply: PopularReply$Type;
declare class Card$Type extends MessageType<Card> {
    constructor();
    create(value?: PartialMessage<Card>): Card;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Card): Card;
    internalBinaryWrite(message: Card, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.show.popular.v1.Card
 */
export declare const Card: Card$Type;
export {};
