// @generated by protobuf-ts 2.9.4 with parameter output_javascript_es2019
// @generated from protobuf file "bilibili/app/show/popular/v1/popular.proto" (package "bilibili.app.show.popular.v1", syntax proto3)
// tslint:disable
import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// @generated message type with reflection information, may provide speed optimized methods
class PopularReply$Type extends MessageType {
    constructor() {
        super("bilibili.app.show.popular.v1.PopularReply", [
            { no: 1, name: "items", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Card }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.items = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target !== null && target !== void 0 ? target : this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated bilibili.app.show.popular.v1.Card items */ 1:
                    message.items.push(Card.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* repeated bilibili.app.show.popular.v1.Card items = 1; */
        for (let i = 0; i < message.items.length; i++)
            Card.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.show.popular.v1.PopularReply
 */
export const PopularReply = new PopularReply$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Card$Type extends MessageType {
    constructor() {
        super("bilibili.app.show.popular.v1.Card", [
            { no: 10, name: "rcmd_one_item", kind: "scalar", oneof: "item", T: 12 /*ScalarType.BYTES*/ },
            { no: 11, name: "small_cover_v5_ad", kind: "scalar", oneof: "item", T: 12 /*ScalarType.BYTES*/ },
            { no: 12, name: "topic_list", kind: "scalar", oneof: "item", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.item = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target !== null && target !== void 0 ? target : this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes rcmd_one_item */ 10:
                    message.item = {
                        oneofKind: "rcmdOneItem",
                        rcmdOneItem: reader.bytes()
                    };
                    break;
                case /* bytes small_cover_v5_ad */ 11:
                    message.item = {
                        oneofKind: "smallCoverV5Ad",
                        smallCoverV5Ad: reader.bytes()
                    };
                    break;
                case /* bytes topic_list */ 12:
                    message.item = {
                        oneofKind: "topicList",
                        topicList: reader.bytes()
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* bytes rcmd_one_item = 10; */
        if (message.item.oneofKind === "rcmdOneItem")
            writer.tag(10, WireType.LengthDelimited).bytes(message.item.rcmdOneItem);
        /* bytes small_cover_v5_ad = 11; */
        if (message.item.oneofKind === "smallCoverV5Ad")
            writer.tag(11, WireType.LengthDelimited).bytes(message.item.smallCoverV5Ad);
        /* bytes topic_list = 12; */
        if (message.item.oneofKind === "topicList")
            writer.tag(12, WireType.LengthDelimited).bytes(message.item.topicList);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.show.popular.v1.Card
 */
export const Card = new Card$Type();
