// @generated by protobuf-ts 2.9.4 with parameter output_javascript_es2019
// @generated from protobuf file "bilibili/app/viewunite/v1/view.proto" (package "bilibili.app.viewunite.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.ViewReply
 */
export interface ViewReply {
    /**
     * @generated from protobuf field: bilibili.app.viewunite.v1.ReqUser req_user = 3;
     */
    reqUser?: ReqUser;
    /**
     * @generated from protobuf field: bilibili.app.viewunite.v1.Tab tab = 5;
     */
    tab?: Tab;
    /**
     * @generated from protobuf field: bytes cm = 7;
     */
    cm: Uint8Array;
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.ReqUser
 */
export interface ReqUser {
    /**
     * @generated from protobuf field: bytes elec_plus_btn = 7;
     */
    elecPlusBtn: Uint8Array;
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.Tab
 */
export interface Tab {
    /**
     * @generated from protobuf field: repeated bilibili.app.viewunite.v1.TabModule tab_module = 1;
     */
    tabModule: TabModule[];
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.TabModule
 */
export interface TabModule {
    /**
     * @generated from protobuf field: bilibili.app.viewunite.v1.TabType tab_type = 1;
     */
    tabType: TabType;
    /**
     * @generated from protobuf oneof: tab
     */
    tab: {
        oneofKind: "introduction";
        /**
         * @generated from protobuf field: bilibili.app.viewunite.v1.IntroductionTab introduction = 2;
         */
        introduction: IntroductionTab;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.IntroductionTab
 */
export interface IntroductionTab {
    /**
     * @generated from protobuf field: repeated bilibili.app.viewunite.v1.Module modules = 2;
     */
    modules: Module[];
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.Module
 */
export interface Module {
    /**
     * @generated from protobuf field: bilibili.app.viewunite.v1.ModuleType type = 1;
     */
    type: ModuleType;
    /**
     * @generated from protobuf oneof: data
     */
    data: {
        oneofKind: "headLine";
        /**
         * @generated from protobuf field: bilibili.app.viewunite.v1.Headline head_line = 5;
         */
        headLine: Headline;
    } | {
        oneofKind: "relates";
        /**
         * @generated from protobuf field: bilibili.app.viewunite.v1.Relates relates = 22;
         */
        relates: Relates;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.Headline
 */
export interface Headline {
    /**
     * @generated from protobuf field: bytes label = 1;
     */
    label: Uint8Array;
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.Relates
 */
export interface Relates {
    /**
     * @generated from protobuf field: repeated bilibili.app.viewunite.v1.RelateCard cards = 1;
     */
    cards: RelateCard[];
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.RelateCard
 */
export interface RelateCard {
    /**
     * @generated from protobuf field: bilibili.app.viewunite.v1.RelateCardType relate_card_type = 1;
     */
    relateCardType: RelateCardType;
    /**
     * @generated from protobuf field: bytes cm_stock = 11;
     */
    cmStock: Uint8Array;
    /**
     * @generated from protobuf field: bilibili.app.viewunite.v1.CardBasicInfo basic_info = 12;
     */
    basicInfo?: CardBasicInfo;
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.CardBasicInfo
 */
export interface CardBasicInfo {
    /**
     * @generated from protobuf field: string unique_id = 6;
     */
    uniqueId: string;
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.ViewProgressReply
 */
export interface ViewProgressReply {
    /**
     * @generated from protobuf field: bytes dm = 4;
     */
    dm: Uint8Array;
}
/**
 * @generated from protobuf message bilibili.app.viewunite.v1.RelatesFeedReply
 */
export interface RelatesFeedReply {
    /**
     * @generated from protobuf field: repeated bilibili.app.viewunite.v1.RelateCard relates = 1;
     */
    relates: RelateCard[];
}
/**
 * @generated from protobuf enum bilibili.app.viewunite.v1.TabType
 */
export declare enum TabType {
    /**
     * @generated from protobuf enum value: TAB_NONE = 0;
     */
    TAB_NONE = 0,
    /**
     * @generated from protobuf enum value: TAB_INTRODUCTION = 1;
     */
    TAB_INTRODUCTION = 1
}
/**
 * @generated from protobuf enum bilibili.app.viewunite.v1.ModuleType
 */
export declare enum ModuleType {
    /**
     * @generated from protobuf enum value: UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: UGC_HEADLINE = 3;
     */
    UGC_HEADLINE = 3,
    /**
     * @generated from protobuf enum value: RELATED_RECOMMEND = 28;
     */
    RELATED_RECOMMEND = 28,
    /**
     * @generated from protobuf enum value: PAY_BAR = 29;
     */
    PAY_BAR = 29,
    /**
     * @generated from protobuf enum value: SPECIALTAG = 37;
     */
    SPECIALTAG = 37,
    /**
     * @generated from protobuf enum value: E55 = 55;
     */
    E55 = 55
}
/**
 * @generated from protobuf enum bilibili.app.viewunite.v1.RelateCardType
 */
export declare enum RelateCardType {
    /**
     * @generated from protobuf enum value: CARD_TYPE_UNKNOWN = 0;
     */
    CARD_TYPE_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: AV = 1;
     */
    AV = 1,
    /**
     * @generated from protobuf enum value: GAME = 4;
     */
    GAME = 4,
    /**
     * @generated from protobuf enum value: CM_TYPE = 5;
     */
    CM_TYPE = 5,
    /**
     * @generated from protobuf enum value: LIVE = 6;
     */
    LIVE = 6,
    /**
     * @generated from protobuf enum value: AI_RECOMMEND = 7;
     */
    AI_RECOMMEND = 7,
    /**
     * @generated from protobuf enum value: COURSE = 11;
     */
    COURSE = 11
}
declare class ViewReply$Type extends MessageType<ViewReply> {
    constructor();
    create(value?: PartialMessage<ViewReply>): ViewReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewReply): ViewReply;
    internalBinaryWrite(message: ViewReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ViewReply
 */
export declare const ViewReply: ViewReply$Type;
declare class ReqUser$Type extends MessageType<ReqUser> {
    constructor();
    create(value?: PartialMessage<ReqUser>): ReqUser;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReqUser): ReqUser;
    internalBinaryWrite(message: ReqUser, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ReqUser
 */
export declare const ReqUser: ReqUser$Type;
declare class Tab$Type extends MessageType<Tab> {
    constructor();
    create(value?: PartialMessage<Tab>): Tab;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Tab): Tab;
    internalBinaryWrite(message: Tab, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.Tab
 */
export declare const Tab: Tab$Type;
declare class TabModule$Type extends MessageType<TabModule> {
    constructor();
    create(value?: PartialMessage<TabModule>): TabModule;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TabModule): TabModule;
    internalBinaryWrite(message: TabModule, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.TabModule
 */
export declare const TabModule: TabModule$Type;
declare class IntroductionTab$Type extends MessageType<IntroductionTab> {
    constructor();
    create(value?: PartialMessage<IntroductionTab>): IntroductionTab;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: IntroductionTab): IntroductionTab;
    internalBinaryWrite(message: IntroductionTab, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.IntroductionTab
 */
export declare const IntroductionTab: IntroductionTab$Type;
declare class Module$Type extends MessageType<Module> {
    constructor();
    create(value?: PartialMessage<Module>): Module;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Module): Module;
    internalBinaryWrite(message: Module, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.Module
 */
export declare const Module: Module$Type;
declare class Headline$Type extends MessageType<Headline> {
    constructor();
    create(value?: PartialMessage<Headline>): Headline;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Headline): Headline;
    internalBinaryWrite(message: Headline, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.Headline
 */
export declare const Headline: Headline$Type;
declare class Relates$Type extends MessageType<Relates> {
    constructor();
    create(value?: PartialMessage<Relates>): Relates;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Relates): Relates;
    internalBinaryWrite(message: Relates, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.Relates
 */
export declare const Relates: Relates$Type;
declare class RelateCard$Type extends MessageType<RelateCard> {
    constructor();
    create(value?: PartialMessage<RelateCard>): RelateCard;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RelateCard): RelateCard;
    internalBinaryWrite(message: RelateCard, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.RelateCard
 */
export declare const RelateCard: RelateCard$Type;
declare class CardBasicInfo$Type extends MessageType<CardBasicInfo> {
    constructor();
    create(value?: PartialMessage<CardBasicInfo>): CardBasicInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CardBasicInfo): CardBasicInfo;
    internalBinaryWrite(message: CardBasicInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.CardBasicInfo
 */
export declare const CardBasicInfo: CardBasicInfo$Type;
declare class ViewProgressReply$Type extends MessageType<ViewProgressReply> {
    constructor();
    create(value?: PartialMessage<ViewProgressReply>): ViewProgressReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewProgressReply): ViewProgressReply;
    internalBinaryWrite(message: ViewProgressReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.ViewProgressReply
 */
export declare const ViewProgressReply: ViewProgressReply$Type;
declare class RelatesFeedReply$Type extends MessageType<RelatesFeedReply> {
    constructor();
    create(value?: PartialMessage<RelatesFeedReply>): RelatesFeedReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RelatesFeedReply): RelatesFeedReply;
    internalBinaryWrite(message: RelatesFeedReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.viewunite.v1.RelatesFeedReply
 */
export declare const RelatesFeedReply: RelatesFeedReply$Type;
export {};
