// @generated by protobuf-ts 2.9.4 with parameter output_javascript_es2019
// @generated from protobuf file "bilibili/playershared/playershared.proto" (package "bilibili.playershared", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message bilibili.playershared.PlayArcConf
 */
export interface PlayArcConf {
    /**
     * @generated from protobuf field: map<int32, bilibili.playershared.ArcConf> arc_confs = 1;
     */
    arcConfs: {
        [key: number]: ArcConf;
    };
}
/**
 * @generated from protobuf message bilibili.playershared.ArcConf
 */
export interface ArcConf {
    /**
     * @generated from protobuf field: bool is_support = 1;
     */
    isSupport: boolean;
    /**
     * @generated from protobuf field: bool disabled = 2;
     */
    disabled: boolean;
    /**
     * @generated from protobuf field: bilibili.playershared.ExtraContent extra_content = 3;
     */
    extraContent?: ExtraContent;
    /**
     * @generated from protobuf field: repeated int32 unsupport_scene = 4;
     */
    unsupportScene: number[];
}
/**
 * @generated from protobuf message bilibili.playershared.ExtraContent
 */
export interface ExtraContent {
    /**
     * @generated from protobuf field: string disable_reason = 1;
     */
    disableReason: string;
    /**
     * @generated from protobuf field: int64 disable_code = 2;
     */
    disableCode: bigint;
}
/**
 * @generated from protobuf message bilibili.playershared.ViewInfo
 */
export interface ViewInfo {
    /**
     * @generated from protobuf field: bytes prompt_bar = 2;
     */
    promptBar: Uint8Array;
}
declare class PlayArcConf$Type extends MessageType<PlayArcConf> {
    constructor();
    create(value?: PartialMessage<PlayArcConf>): PlayArcConf;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayArcConf): PlayArcConf;
    private binaryReadMap1;
    internalBinaryWrite(message: PlayArcConf, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.playershared.PlayArcConf
 */
export declare const PlayArcConf: PlayArcConf$Type;
declare class ArcConf$Type extends MessageType<ArcConf> {
    constructor();
    create(value?: PartialMessage<ArcConf>): ArcConf;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ArcConf): ArcConf;
    internalBinaryWrite(message: ArcConf, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.playershared.ArcConf
 */
export declare const ArcConf: ArcConf$Type;
declare class ExtraContent$Type extends MessageType<ExtraContent> {
    constructor();
    create(value?: PartialMessage<ExtraContent>): ExtraContent;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ExtraContent): ExtraContent;
    internalBinaryWrite(message: ExtraContent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.playershared.ExtraContent
 */
export declare const ExtraContent: ExtraContent$Type;
declare class ViewInfo$Type extends MessageType<ViewInfo> {
    constructor();
    create(value?: PartialMessage<ViewInfo>): ViewInfo;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewInfo): ViewInfo;
    internalBinaryWrite(message: ViewInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.playershared.ViewInfo
 */
export declare const ViewInfo: ViewInfo$Type;
export {};
