// @generated by protobuf-ts 2.9.4 with parameter output_javascript_es2019
// @generated from protobuf file "bilibili/app/view/v1/view.proto" (package "bilibili.app.view.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message bilibili.app.view.v1.ViewReply
 */
export interface ViewReply {
    /**
     * @generated from protobuf field: bilibili.app.view.v1.ReqUser req_user = 4;
     */
    reqUser?: ReqUser;
    /**
     * @generated from protobuf field: repeated bilibili.app.view.v1.Relate relates = 10;
     */
    relates: Relate[];
    /**
     * @generated from protobuf field: bytes label = 23;
     */
    label: Uint8Array;
    /**
     * @generated from protobuf field: repeated bytes cms = 30;
     */
    cms: Uint8Array[];
    /**
     * @generated from protobuf field: bytes cm_config = 31;
     */
    cmConfig: Uint8Array;
    /**
     * @generated from protobuf field: bytes cm_ipad = 41;
     */
    cmIpad: Uint8Array;
    /**
     * @generated from protobuf field: repeated bytes special_cell_new = 50;
     */
    specialCellNew: Uint8Array[];
}
/**
 * @generated from protobuf message bilibili.app.view.v1.ReqUser
 */
export interface ReqUser {
    /**
     * @generated from protobuf field: bytes elec_plus_btn = 9;
     */
    elecPlusBtn: Uint8Array;
}
/**
 * @generated from protobuf message bilibili.app.view.v1.Relate
 */
export interface Relate {
    /**
     * @generated from protobuf field: bytes cm = 28;
     */
    cm: Uint8Array;
}
/**
 * @generated from protobuf message bilibili.app.view.v1.ViewProgressReply
 */
export interface ViewProgressReply {
    /**
     * @generated from protobuf field: bytes video_guide = 1;
     */
    videoGuide: Uint8Array;
}
/**
 * @generated from protobuf message bilibili.app.view.v1.TFInfoReply
 */
export interface TFInfoReply {
    /**
     * @generated from protobuf field: int64 tips_id = 1;
     */
    tipsId: bigint;
    /**
     * @generated from protobuf field: bytes tf_toast = 2;
     */
    tfToast: Uint8Array;
    /**
     * @generated from protobuf field: bytes tf_panel_customized = 3;
     */
    tfPanelCustomized: Uint8Array;
}
declare class ViewReply$Type extends MessageType<ViewReply> {
    constructor();
    create(value?: PartialMessage<ViewReply>): ViewReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewReply): ViewReply;
    internalBinaryWrite(message: ViewReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.ViewReply
 */
export declare const ViewReply: ViewReply$Type;
declare class ReqUser$Type extends MessageType<ReqUser> {
    constructor();
    create(value?: PartialMessage<ReqUser>): ReqUser;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReqUser): ReqUser;
    internalBinaryWrite(message: ReqUser, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.ReqUser
 */
export declare const ReqUser: ReqUser$Type;
declare class Relate$Type extends MessageType<Relate> {
    constructor();
    create(value?: PartialMessage<Relate>): Relate;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Relate): Relate;
    internalBinaryWrite(message: Relate, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.Relate
 */
export declare const Relate: Relate$Type;
declare class ViewProgressReply$Type extends MessageType<ViewProgressReply> {
    constructor();
    create(value?: PartialMessage<ViewProgressReply>): ViewProgressReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ViewProgressReply): ViewProgressReply;
    internalBinaryWrite(message: ViewProgressReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.ViewProgressReply
 */
export declare const ViewProgressReply: ViewProgressReply$Type;
declare class TFInfoReply$Type extends MessageType<TFInfoReply> {
    constructor();
    create(value?: PartialMessage<TFInfoReply>): TFInfoReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TFInfoReply): TFInfoReply;
    internalBinaryWrite(message: TFInfoReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.view.v1.TFInfoReply
 */
export declare const TFInfoReply: TFInfoReply$Type;
export {};
