// @generated by protobuf-ts 2.9.4 with parameter output_javascript_es2019
// @generated from protobuf file "bilibili/community/service/dm/v1/dm.proto" (package "bilibili.community.service.dm.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message bilibili.community.service.dm.v1.DmViewReply
 */
export interface DmViewReply {
    /**
     * @generated from protobuf field: repeated string activity_meta = 18;
     */
    activityMeta: string[];
    /**
     * @generated from protobuf field: bilibili.community.service.dm.v1.Command command = 22;
     */
    command?: Command;
}
/**
 * @generated from protobuf message bilibili.community.service.dm.v1.Command
 */
export interface Command {
    /**
     * @generated from protobuf field: repeated bytes commandDms = 1;
     */
    commandDms: Uint8Array[];
}
declare class DmViewReply$Type extends MessageType<DmViewReply> {
    constructor();
    create(value?: PartialMessage<DmViewReply>): DmViewReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DmViewReply): DmViewReply;
    internalBinaryWrite(message: DmViewReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.community.service.dm.v1.DmViewReply
 */
export declare const DmViewReply: DmViewReply$Type;
declare class Command$Type extends MessageType<Command> {
    constructor();
    create(value?: PartialMessage<Command>): Command;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Command): Command;
    internalBinaryWrite(message: Command, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.community.service.dm.v1.Command
 */
export declare const Command: Command$Type;
export {};
