// @generated by protobuf-ts 2.9.4 with parameter output_javascript_es2019
// @generated from protobuf file "bilibili/main/community/reply/v1/reply.proto" (package "bilibili.main.community.reply.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message bilibili.main.community.reply.v1.MainListReply
 */
export interface MainListReply {
    /**
     * @generated from protobuf field: bytes cm = 11;
     */
    cm: Uint8Array;
}
declare class MainListReply$Type extends MessageType<MainListReply> {
    constructor();
    create(value?: PartialMessage<MainListReply>): MainListReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MainListReply): MainListReply;
    internalBinaryWrite(message: MainListReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.main.community.reply.v1.MainListReply
 */
export declare const MainListReply: MainListReply$Type;
export {};
