// @generated by protobuf-ts 2.9.4 with parameter output_javascript_es2019
// @generated from protobuf file "bilibili/polymer/app/search/v1/search.proto" (package "bilibili.polymer.app.search.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message bilibili.polymer.app.search.v1.SearchAllResponse
 */
export interface SearchAllResponse {
    /**
     * @generated from protobuf field: repeated bilibili.polymer.app.search.v1.Item item = 4;
     */
    item: Item[];
}
/**
 * @generated from protobuf message bilibili.polymer.app.search.v1.Item
 */
export interface Item {
    /**
     * @generated from protobuf field: string linktype = 4;
     */
    linktype: string;
}
declare class SearchAllResponse$Type extends MessageType<SearchAllResponse> {
    constructor();
    create(value?: PartialMessage<SearchAllResponse>): SearchAllResponse;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SearchAllResponse): SearchAllResponse;
    internalBinaryWrite(message: SearchAllResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.polymer.app.search.v1.SearchAllResponse
 */
export declare const SearchAllResponse: SearchAllResponse$Type;
declare class Item$Type extends MessageType<Item> {
    constructor();
    create(value?: PartialMessage<Item>): Item;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Item): Item;
    internalBinaryWrite(message: Item, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.polymer.app.search.v1.Item
 */
export declare const Item: Item$Type;
export {};
