// @generated by protobuf-ts 2.9.4 with parameter output_javascript_es2019
// @generated from protobuf file "bilibili/app/interface/v1/search.proto" (package "bilibili.app.interface.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message bilibili.app.interface.v1.DefaultWordsReply
 */
export interface DefaultWordsReply {
    /**
     * @generated from protobuf field: string show = 3;
     */
    show: string;
    /**
     * @generated from protobuf field: string word = 4;
     */
    word: string;
    /**
     * @generated from protobuf field: string goto = 7;
     */
    goto: string;
    /**
     * @generated from protobuf field: string value = 8;
     */
    value: string;
    /**
     * @generated from protobuf field: string uri = 9;
     */
    uri: string;
}
declare class DefaultWordsReply$Type extends MessageType<DefaultWordsReply> {
    constructor();
    create(value?: PartialMessage<DefaultWordsReply>): DefaultWordsReply;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DefaultWordsReply): DefaultWordsReply;
    internalBinaryWrite(message: DefaultWordsReply, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message bilibili.app.interface.v1.DefaultWordsReply
 */
export declare const DefaultWordsReply: DefaultWordsReply$Type;
export {};
