// @generated by protobuf-ts 2.9.4 with parameter output_javascript_es2019
// @generated from protobuf file "bilibili/app/interface/v1/search.proto" (package "bilibili.app.interface.v1", syntax proto3)
// tslint:disable
import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// @generated message type with reflection information, may provide speed optimized methods
class DefaultWordsReply$Type extends MessageType {
    constructor() {
        super("bilibili.app.interface.v1.DefaultWordsReply", [
            { no: 3, name: "show", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "word", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "goto", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "value", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "uri", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.show = "";
        message.word = "";
        message.goto = "";
        message.value = "";
        message.uri = "";
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target !== null && target !== void 0 ? target : this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string show */ 3:
                    message.show = reader.string();
                    break;
                case /* string word */ 4:
                    message.word = reader.string();
                    break;
                case /* string goto */ 7:
                    message.goto = reader.string();
                    break;
                case /* string value */ 8:
                    message.value = reader.string();
                    break;
                case /* string uri */ 9:
                    message.uri = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* string show = 3; */
        if (message.show !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.show);
        /* string word = 4; */
        if (message.word !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.word);
        /* string goto = 7; */
        if (message.goto !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.goto);
        /* string value = 8; */
        if (message.value !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.value);
        /* string uri = 9; */
        if (message.uri !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.uri);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bilibili.app.interface.v1.DefaultWordsReply
 */
export const DefaultWordsReply = new DefaultWordsReply$Type();
